test: &test
  adapter: mysql2
  database: <%= ENV.fetch('IRONTRAIL_CI_DATABASE', 'iron_trail_test') %>
  username: <%= ENV.fetch('IRONTRAIL_CI_DB_USER', 'root') %>
  password: <%= ENV.fetch('IRONTRAIL_CI_DB_PASSWORD', '') %>
  host: <%= ENV.fetch('IRONTRAIL_CI_DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('IRONTRAIL_CI_DB_PORT', 3306) %>
  encoding: utf8mb4
  collation: utf8mb4_0900_ai_ci
