name: test
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}.gemfile, MySQL ${{ matrix.mysql }}
    runs-on: ubuntu-latest
    services:
      test-mysql:
        image: mysql:${{ matrix.mysql }}
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: foobar123
          MYSQL_DATABASE: iron_trail_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        include:
        # old
        - { gemfile: 'rails_7.1', ruby: '3.3', mysql: '8.0' }
        - { gemfile: 'rails_7.2', ruby: '3.3', mysql: '8.0' }
        # current
        - { gemfile: 'rails_8.0', ruby: '3.4', mysql: '8.0' }
        - { gemfile: 'rails_8.0', ruby: '3.4', mysql: '8.4' }
        - { gemfile: 'rails_8.1', ruby: '3.4', mysql: '8.4' }
        # futuristic
        - { gemfile: 'rails_8.1', ruby: 'head', mysql: '8.4', experimental: true }
        - { gemfile: 'rails_head', ruby: 'head', mysql: '8.4', experimental: true }
    continue-on-error: ${{ matrix.experimental || false }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v6
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    - name: Run specs
      run:
        bundle exec rake install_database_yml spec && bundle exec rake testing_spec
      env:
        BACKTRACE: 1
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
        DB: mysql
        IRONTRAIL_CI_DATABASE: iron_trail_test
        IRONTRAIL_CI_DB_USER: root
        IRONTRAIL_CI_DB_PASSWORD: foobar123
        IRONTRAIL_CI_DB_HOST: 127.0.0.1
        IRONTRAIL_CI_DB_PORT: 3306
